//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl.
        /// </summary>
        public static string MWBTNCrawl {
            get {
                return ResourceManager.GetString("MWBTNCrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MWMAbout {
            get {
                return ResourceManager.GetString("MWMAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MWMClose {
            get {
                return ResourceManager.GetString("MWMClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MWMFiles {
            get {
                return ResourceManager.GetString("MWMFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MWMOptions {
            get {
                return ResourceManager.GetString("MWMOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl.
        /// </summary>
        public static string MWTCDGCrawlHeader {
            get {
                return ResourceManager.GetString("MWTCDGCrawlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MWTCDGDateHeader {
            get {
                return ResourceManager.GetString("MWTCDGDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string MWTCDGEncodingHeader {
            get {
                return ResourceManager.GetString("MWTCDGEncodingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to innerHTML.
        /// </summary>
        public static string MWTCDGInnerHTMLHeader {
            get {
                return ResourceManager.GetString("MWTCDGInnerHTMLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string MWTCDGLinkHeader {
            get {
                return ResourceManager.GetString("MWTCDGLinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outerHTML.
        /// </summary>
        public static string MWTCDGOuterHTMLHeader {
            get {
                return ResourceManager.GetString("MWTCDGOuterHTMLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string MWTCDGSelectorsButtonShow {
            get {
                return ResourceManager.GetString("MWTCDGSelectorsButtonShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectors.
        /// </summary>
        public static string MWTCDGSelectorsHeader {
            get {
                return ResourceManager.GetString("MWTCDGSelectorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string MWTCDGStatusHeader {
            get {
                return ResourceManager.GetString("MWTCDGStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string MWTCDGTextHeader {
            get {
                return ResourceManager.GetString("MWTCDGTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total selectors.
        /// </summary>
        public static string MWTCDGTotalSelectorsHeader {
            get {
                return ResourceManager.GetString("MWTCDGTotalSelectorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim.
        /// </summary>
        public static string MWTCDGTrimHeader {
            get {
                return ResourceManager.GetString("MWTCDGTrimHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename group.
        /// </summary>
        public static string MWTCOGroupname {
            get {
                return ResourceManager.GetString("MWTCOGroupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group(s).
        /// </summary>
        public static string MWTCOGroupNames {
            get {
                return ResourceManager.GetString("MWTCOGroupNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link(s).
        /// </summary>
        public static string MWTCOLinks {
            get {
                return ResourceManager.GetString("MWTCOLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MWTCOSearch {
            get {
                return ResourceManager.GetString("MWTCOSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string MWTCTIFiles {
            get {
                return ResourceManager.GetString("MWTCTIFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups / Links.
        /// </summary>
        public static string MWTCTIGroupsLinks {
            get {
                return ResourceManager.GetString("MWTCTIGroupsLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Selectors.
        /// </summary>
        public static string MWTCTIImportSelectors {
            get {
                return ResourceManager.GetString("MWTCTIImportSelectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkgrabber.
        /// </summary>
        public static string MWTCTILinkGrabber {
            get {
                return ResourceManager.GetString("MWTCTILinkGrabber", resourceCulture);
            }
        }
    }
}
