//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWC.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crawl ähnelt.
        /// </summary>
        public static string MWBTNCrawl {
            get {
                return ResourceManager.GetString("MWBTNCrawl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string MWMAbout {
            get {
                return ResourceManager.GetString("MWMAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string MWMClose {
            get {
                return ResourceManager.GetString("MWMClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string MWMFiles {
            get {
                return ResourceManager.GetString("MWMFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string MWMOptions {
            get {
                return ResourceManager.GetString("MWMOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crawl ähnelt.
        /// </summary>
        public static string MWTCDGCrawlHeader {
            get {
                return ResourceManager.GetString("MWTCDGCrawlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string MWTCDGDateHeader {
            get {
                return ResourceManager.GetString("MWTCDGDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encoding ähnelt.
        /// </summary>
        public static string MWTCDGEncodingHeader {
            get {
                return ResourceManager.GetString("MWTCDGEncodingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die innerHTML ähnelt.
        /// </summary>
        public static string MWTCDGInnerHTMLHeader {
            get {
                return ResourceManager.GetString("MWTCDGInnerHTMLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link ähnelt.
        /// </summary>
        public static string MWTCDGLinkHeader {
            get {
                return ResourceManager.GetString("MWTCDGLinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die outerHTML ähnelt.
        /// </summary>
        public static string MWTCDGOuterHTMLHeader {
            get {
                return ResourceManager.GetString("MWTCDGOuterHTMLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show ähnelt.
        /// </summary>
        public static string MWTCDGSelectorsButtonShow {
            get {
                return ResourceManager.GetString("MWTCDGSelectorsButtonShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selectors ähnelt.
        /// </summary>
        public static string MWTCDGSelectorsHeader {
            get {
                return ResourceManager.GetString("MWTCDGSelectorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string MWTCDGStatusHeader {
            get {
                return ResourceManager.GetString("MWTCDGStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        public static string MWTCDGTextHeader {
            get {
                return ResourceManager.GetString("MWTCDGTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total selectors ähnelt.
        /// </summary>
        public static string MWTCDGTotalSelectorsHeader {
            get {
                return ResourceManager.GetString("MWTCDGTotalSelectorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trim ähnelt.
        /// </summary>
        public static string MWTCDGTrimHeader {
            get {
                return ResourceManager.GetString("MWTCDGTrimHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        public static string MWTCOGroupname {
            get {
                return ResourceManager.GetString("MWTCOGroupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Groupname(s) ähnelt.
        /// </summary>
        public static string MWTCOGroupNames {
            get {
                return ResourceManager.GetString("MWTCOGroupNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Links ähnelt.
        /// </summary>
        public static string MWTCOLinks {
            get {
                return ResourceManager.GetString("MWTCOLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string MWTCOSearch {
            get {
                return ResourceManager.GetString("MWTCOSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Files ähnelt.
        /// </summary>
        public static string MWTCTIFiles {
            get {
                return ResourceManager.GetString("MWTCTIFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Groups / Links ähnelt.
        /// </summary>
        public static string MWTCTIGroupsLinks {
            get {
                return ResourceManager.GetString("MWTCTIGroupsLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Selectors ähnelt.
        /// </summary>
        public static string MWTCTIImportSelectors {
            get {
                return ResourceManager.GetString("MWTCTIImportSelectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linkgrabber ähnelt.
        /// </summary>
        public static string MWTCTILinkGrabber {
            get {
                return ResourceManager.GetString("MWTCTILinkGrabber", resourceCulture);
            }
        }
    }
}
